import {Platform, Dimensions} from 'react-native';
import helpers from '../../helpers';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const {width, height} = Dimensions.get('window');

export default {
  shell: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: wp(5),
    paddingTop: Platform.OS === 'ios' ? hp('8%') : hp('2%'),
    paddingBottom: 200,
  },
  containerWithEmail: {
    flex: 1,
    height: height,
  },
  textTitleWithEmail: {
    fontSize: helpers.scaling.moderateScale(20),
    color: '#565454',
    letterSpacing: 0.34,
    fontWeight: 'bold',
  },
  textSales: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    marginTop: hp(0.5),
    letterSpacing: 0.34,
    fontWeight: '400',
  },
  textMenu: {
    fontSize: helpers.scaling.moderateScale(13),
    color: '#565454',
    marginTop: hp(0.8),
    letterSpacing: 0.34,
    fontWeight: '500',
  },
  containerSales: {
    backgroundColor: '#FFEBF0',
    paddingHorizontal: 4,
    paddingVertical: 10,
    width: wp(36),
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    marginTop: hp(1.5),
  },
  textSalesValue: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#ff3e6c',
    letterSpacing: 0.34,
    fontWeight: 'bold',
  },
  textCurrency: {
    fontSize: helpers.scaling.moderateScale(12),
    color: '#ff3e6c',
    letterSpacing: 0.34,
    marginBottom: 8,
    marginRight: 5,
  },
  textSalesValueWhite: {
    fontSize: helpers.scaling.moderateScale(22),
    color: 'white',
    letterSpacing: 0.34,
    fontWeight: 'bold',
  },
  textCurrencyWhite: {
    fontSize: helpers.scaling.moderateScale(12),
    color: 'white',
    letterSpacing: 0.34,
    marginRight: 5,
  },
  textSalesValueWhiteSmall: {
    fontSize: helpers.scaling.moderateScale(10),
    color: 'white',
    letterSpacing: 0.34,
    fontWeight: 'bold',
  },
  textCurrencyWhiteSmall: {
    fontSize: helpers.scaling.moderateScale(8),
    color: 'white',
    letterSpacing: 0.34,
    marginRight: 5,
  },
  textTotalSalesSmall: {
    fontSize: helpers.scaling.moderateScale(11),
    color: 'white',
    marginTop: hp(0.5),
    letterSpacing: 0.34,
    fontWeight: '400',
  },
  textTotalSales: {
    fontSize: helpers.scaling.moderateScale(14),
    color: 'white',
    marginTop: hp(3),
    letterSpacing: 0.34,
    fontWeight: '500',
  },
  textTitleInfo: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    letterSpacing: 0.34,
    fontWeight: 'bold',
    marginTop: hp(3),
  },
  textWelcome: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    marginTop: hp(0.5),
    letterSpacing: 0.34,
    fontWeight: '400',
  },
  textTitle: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    letterSpacing: 0.34,
    fontWeight: 'bold',
    marginTop: 12,
  },
  textSubtitle: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    marginTop: hp(0.5),
    letterSpacing: 0.34,
    fontWeight: '400',
  },
  borderText: {
    height: 1,
    backgroundColor: '#E8EBEB',
    marginTop: 16,
    marginBottom: 4,
    marginHorizontal: -30,
  },
  borderText2: {
    height: 1,
    backgroundColor: '#E8EBEB',
    marginTop: 16,
    marginBottom: 4,
    marginLeft: wp(15),
  },
  containerFeature: {
    flexDirection: 'row',
    maxWidth: wp(76),
  },
  containerImageFeature: {
    width: 50,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    marginTop: 12,
    marginRight: 10,
    backgroundColor: '#f6f7f7',
  },
  imageFeature: {
    width: 24,
    height: 24,
    alignSelf: 'center',
    tintColor: '#2D2D2D',
    resizeMode: 'contain',
  },
  textTitleToko: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    letterSpacing: 0.34,
    fontWeight: 'bold',
  },
  imageCopy: {
    width: 18,
    height: 18,
    marginTop: hp(0.7),
    resizeMode: 'contain',
    marginLeft: 6,
  },
  containerCardToko: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 2,
    marginHorizontal: 2,
    borderRadius: 12,
    backgroundColor: 'white',
    marginTop: 16,
    justifyContent: 'center',
    padding: 12,
    marginBottom: 8,
  },
  textSubtitleShareMenuBold: {
    fontSize: helpers.scaling.moderateScale(14),
    color: '#565454',
    letterSpacing: 0.34,
    marginTop: hp(0.5),
    textAlign: 'center',
  },
};
